### ISSUE TITLE
Plural - Singular conversion

### ISSUE THREAD

**Issue by premasundari-m** [AlexChristensen/SemNetDictionaries#2]
I am using the function named "singularize" from SemNetCleaner package.
I try to convert plural words into singular form using this function.
But few words are not properly converted into the singular form like 
sales converted to sal
houses converted to houses
 Is there any dictionary which already exists to solve this?
Kindly help me with this issue

**Comment by AlexChristensen** [comment]
@premasundari-m,

Please download the latest *SemNetCleaner* from GitHub: `devtools::install_github("AlexChristensen/SemNetCleaner")`
